### PR TITLE
Changes for Kubernetes support

### PR DESCRIPTION
**Pull request by nevets963**

### CODE REVIEW

**Comment by Cloud-Chen** [comment]
test pull request

**Comment by Cloud-Chen** [comment]
Can one of the admins verify this patch?

**Comment by Cloud-Chen** [comment]
Ok to test

**Comment by Cloud-Chen** [comment]
Ok to test

**Comment by Cloud-Chen** [comment]
Ok to test

**Comment by Cloud-Chen** [comment]
Ok to test

**Comment by Cloud-Chen** [comment]
Ok to test

**Comment by Cloud-Chen** [comment]
Can one of the admins verify this patch?

**Comment by wagmarcel** [comment]
ok to test

**Pull request closed without merging**
