### PR TITLE
Remove postgres pre-defined function dependency

### PR DESCRIPTION
**Pull request by oguzcankirmemis**
Signed-off-by: Oguzcan Kirmemis <oguzcan.kirmemis@gmail.com>

### CODE REVIEW

**Comment by oguzcankirmemis** [comment]
Should be merged after circleci PR #27

**Comment by oguzcankirmemis** [comment]
@wagmarcel ok to merge

**Comment by oguzcankirmemis** [comment]
@wagmarcel Before merging the frontend PR [#138](https://github.com/Open-IoT-Service-Platform/oisp-frontend/pull/138), this is the last one we have to merge, I am restarting tests, so it is confirmed that this passes after the recent merge at the platform launcher.

**Comment by oguzcankirmemis** [comment]
ok to merge

**Review by wagmarcel — APPROVED** [review]

**Pull request merged**
